spring.application.name=digitalfix-ms-bff

server.port=8081

services.workorders.url=${WORKORDERS_URL:http://localhost:8080}
services.catalog.url=${CATALOG_URL:http://localhost:8082}

azure.tenant-id=${AZURE_TENANT_ID:e41d6238-6d3e-4375-9eab-dac7f51fe731}
azure.client-id=${AZURE_CLIENT_ID:fad2db65-7d82-41d8-a0c5-2fa1e2512ee4}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${azure.tenant-id}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=${azure.client-id}